Repository IF-107-Ruby/paw-patrol, pull requests merged in 2020-04, with the labels that each got.

#3 Add configurations for travis ci and rubocop
  .rubocop.yml
  .travis.yml
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/puma.rb
  config/spring.rb
  db/schema.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/capybara.rb
  spec/support/shoulda_matchers.rb
  spec/support/simplecov.rb
Labels: ready for review

#6 Postgresql
  .gitignore
  Gemfile
  Gemfile.lock
  config/database.yml
  config/database.yml.example
Labels: ready for review

#10 Add database configurations for travis ci
  .travis.yml
  config/database.yml.travis
Labels: ready for review

#7 Bootstrap reconecting and landing layout perfomance
  .travis.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/home.scss
  app/controllers/home_controller.rb
  app/helpers/home_helper.rb
  app/javascript/packs/application.js
  app/views/home/index.html.slim
  app/views/layouts/_footer.html.slim
  app/views/layouts/_meta.html.slim
  app/views/layouts/_nav.html.slim
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.slim
  config/routes.rb
  spec/helpers/home_helper_spec.rb
  spec/requests/home_request_spec.rb
  spec/views/home/index.html.erb_spec.rb
Labels: Changes Requested

#8 Feature/company crud
  app/assets/stylesheets/companies.scss
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/form.scss
  app/assets/stylesheets/home.scss
  app/controllers/companies_controller.rb
  app/helpers/companies_helper.rb
  app/models/company.rb
  app/views/companies/_company.html.slim
  app/views/companies/_form.html.slim
  app/views/companies/edit.html.slim
  app/views/companies/index.html.slim
  app/views/companies/new.html.slim
  app/views/companies/show.html.slim
  app/views/layouts/_flash.html.slim
  app/views/layouts/application.html.slim
  app/views/shared/_error_messages.html.slim
  config/routes.rb
  db/migrate/20200411055059_create_companies.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/companies_controller_spec.rb
  spec/factories/companies.rb
  spec/features/create_company_spec.rb
  spec/helpers/companies_helper_spec.rb
  spec/models/company_spec.rb
  spec/requests/companies_request_spec.rb
Labels: ready for review

#5 Unit crud
  .rubocop.yml
  app/assets/stylesheets/units.scss
  app/controllers/units_controller.rb
  app/helpers/units_helper.rb
  app/models/unit.rb
  app/views/units/_unit.html.slim
  app/views/units/_unit_form.html.slim
  app/views/units/edit.html.slim
  app/views/units/index.html.slim
  app/views/units/new.html.slim
  app/views/units/show.html.slim
  config/database.yml.example
  config/routes.rb
  db/migrate/20200411125438_create_units.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/units_controller_spec.rb
  spec/factories/units.rb
  spec/features/unit_crud_spec.rb
  spec/helpers/home_helper_spec.rb
  spec/models/unit_spec.rb
  spec/views/home/index.html.erb_spec.rb
Labels: ready for review

#56 Fix/form errors layout
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/home.scss
  app/views/shared/_error_messages.html.slim
Labels: ready for review

#61 Fix/form errors layout with buttons
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/form.scss
  app/javascript/packs/application.js
  app/models/company.rb
  app/views/companies/_form.html.slim
  app/views/companies/show.html.slim
  spec/features/create_company_spec.rb
  spec/models/company_spec.rb
Labels: ready for review

#62 Feedback
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/feedbacks.scss
  app/controllers/feedbacks_controller.rb
  app/controllers/home_controller.rb
  app/helpers/feedbacks_helper.rb
  app/models/feedback.rb
  app/views/feedbacks/_add_feedback_form.html.slim
  app/views/feedbacks/index.html.slim
  app/views/feedbacks/show.html.slim
  app/views/home/index.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.html.slim
  app/views/layouts/mailer.text.erb
  app/views/layouts/mailer.text.slim
  config/initializers/simple_form.rb
  config/initializers/simple_form_bootstrap.rb
  config/locales/simple_form.en.yml
  config/routes.rb
  db/migrate/20200413070244_create_feedbacks.rb
  db/schema.rb
  db/seeds.rb
  lib/templates/erb/scaffold/_form.html.erb
  spec/controllers/feedbacks_controller_spec.rb
  spec/factories/feedbacks.rb
  spec/features/user_leaves_feedback_spec.rb
  spec/models/feedback_spec.rb
Labels: ready for review

#60 Crud users creation
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/assets/stylesheets/users.scss
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/layouts/_nav.html.slim
  app/views/layouts/mailer.html.slim
  app/views/users/_form.html.slim
  app/views/users/_users.html.slim
  app/views/users/edit.html.slim
  app/views/users/index.html.slim
  app/views/users/new.html.slim
  app/views/users/show.html.slim
  config/application.rb
  config/routes.rb
  db/migrate/20200410161541_create_users.rb
  db/schema.rb
  db/seeds.rb
  lib/templates/slim/scaffold/_form.html.slim
  spec/controllers/users_controller_spec.rb
  spec/factories/users.rb
  spec/features/create_user_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: ready for review

#67 Users companies relationship
  .rubocop.yml
  app/assets/stylesheets/members.scss
  app/controllers/members_controller.rb
  app/controllers/users_controller.rb
  app/helpers/members_helper.rb
  app/helpers/users_helper.rb
  app/models/company.rb
  app/models/user.rb
  app/models/users_companies_relationship.rb
  app/views/companies/show.html.slim
  app/views/members/index.html.slim
  app/views/users/_users.html.slim
  app/views/users/show.html.slim
  config/routes.rb
  db/migrate/20200416072355_change_is_admin_to_be_boolean_in_users.rb
  db/migrate/20200416082345_create_users_companies_relationships.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/members_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/users.rb
  spec/factories/users_companies_relationships.rb
  spec/features/user_looks_information_about_company_other_user_spec.rb
  spec/models/company_spec.rb
  spec/models/user_spec.rb
  spec/models/users_companies_relationship_spec.rb
Labels: ready for review

#64 Adding pagination
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/companies_controller.rb
  app/controllers/feedbacks_controller.rb
  app/controllers/units_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/companies/index.html.slim
  app/views/feedbacks/index.html.slim
  app/views/units/index.html.slim
  app/views/users/index.html.slim
  config/initializers/pagy.rb
Labels: ready for review

#71 Fix/bootstap jquery
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  config/webpack/environment.js
  package.json
  yarn.lock
Labels: ready for review

#68 Feature/unit tree structure
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/units.scss
  app/controllers/units_controller.rb
  app/models/unit.rb
  app/views/units/_unit.html.slim
  app/views/units/_unit_form.html.slim
  app/views/units/_unit_tree_structure.html.slim
  app/views/units/index.html.slim
  app/views/units/show.html.slim
  db/migrate/20200416071812_add_ancestry_to_units.rb
  db/schema.rb
  spec/factories/units.rb
  spec/models/unit_spec.rb
Labels: ready for review

#69 Company unit association
  Gemfile.lock
  app/controllers/units_controller.rb
  app/models/company.rb
  app/models/unit.rb
  app/views/companies/show.html.slim
  app/views/units/_unit.html.slim
  app/views/units/_unit_form.html.slim
  app/views/units/index.html.slim
  app/views/units/show.html.slim
  config/routes.rb
  db/migrate/20200415081615_add_company_to_units.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/units_controller_spec.rb
  spec/factories/companies.rb
  spec/factories/units.rb
  spec/features/unit_crud_spec.rb
  spec/models/company_spec.rb
  spec/models/unit_spec.rb
Labels: ready for review

#74 fix/basic-style
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/errors.scss
  app/assets/stylesheets/feedbacks.scss
  app/assets/stylesheets/form.scss
  app/assets/stylesheets/units.scss
  app/assets/stylesheets/users.scss
  app/views/errors/not_found.html.slim
  app/views/errors/server_errors.html.slim
  app/views/home/index.html.slim
  app/views/layouts/_footer.html.slim
  app/views/layouts/_nav.html.slim
  app/views/layouts/application.html.slim
  app/views/units/new.html.slim
  app/views/units/show.html.slim
  app/views/users/_form.html.slim
  app/views/users/edit.html.slim
  app/views/users/index.html.slim
  app/views/users/new.html.slim
Labels: ready for review

#70 Fix/users companies relationship
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/members_controller.rb
  app/decorators/user_decorator.rb
  app/helpers/users_helper.rb
  app/models/company.rb
  app/views/members/_member.html.slim
  app/views/members/index.html.slim
  db/seeds.rb
  spec/controllers/members_controller_spec.rb
  spec/decorators/user_decorator_spec.rb
  spec/factories/users_companies_relationships.rb
Labels: ready for review

#76 Feature/company registrations
  Gemfile
  Gemfile.lock
  app/controllers/companies_controller.rb
  app/controllers/users_controller.rb
  app/forms/company_registrations_form.rb
  app/models/user.rb
  app/views/companies/_company_registration_form.slim
  app/views/companies/new.html.slim
  app/views/devise/sessions/new.html.slim
  app/views/layouts/_nav.html.slim
  app/views/users/_form.html.slim
  app/views/users/edit.html.slim
  app/views/users/new.html.slim
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20200423055316_add_devise_to_users.rb
  db/migrate/20200423170838_add_default_value_for_role_to_users_companies_relationship.rb
  db/schema.rb
  spec/controllers/companies_controller_spec.rb
  spec/factories/companies.rb
  spec/factories/company_registrations_form.rb
  spec/factories/users.rb
  spec/features/company_registration_spec.rb
  spec/features/create_company_spec.rb
  spec/features/create_user_spec.rb
  spec/helpers/errors_helper_spec.rb
Labels: Changes Requested, ready for review

#78 Feature/static pages
  .gitignore
  app/assets/images/about_img1.jpg
  app/assets/images/about_img2.jpg
  app/assets/images/services_img.jpg
  app/assets/stylesheets/home.scss
  app/assets/stylesheets/static_pages.scss
  app/assets/stylesheets/users.scss
  app/controllers/feedbacks_controller.rb
  app/controllers/home_controller.rb
  app/controllers/static_pages_controller.rb
  app/helpers/static_pages_helper.rb
  app/views/feedbacks/_add_feedback_form.html.slim
  app/views/home/index.html.slim
  app/views/layouts/_nav.html.slim
  app/views/static_pages/about.html.slim
  app/views/static_pages/contact.html.slim
  app/views/static_pages/services.html.slim
  config/routes.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/features/user_leaves_feedback_spec.rb
  spec/helpers/static_pages_helper_spec.rb
  spec/requests/static_pages_request_spec.rb
  spec/views/static_pages/about.html.slim_spec.rb
  spec/views/static_pages/contact.html.slim_spec.rb
  spec/views/static_pages/services.html.slim_spec.rb
Labels: ready for review

#79 Feedbacks policies
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/feedbacks_controller.rb
  app/policies/application_policy.rb
  app/policies/feedback_policy.rb
  app/views/layouts/_nav.html.slim
  db/seeds.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/features/user_visit_feedbacks_page_spec.rb
  spec/policies/feedback_policy_spec.rb
  spec/rails_helper.rb
  spec/support/devise.rb
Labels: ready for review

#81 Cleaning up the project
  app/controllers/static_pages_controller.rb
  app/controllers/users_controller.rb
  app/helpers/companies_helper.rb
  app/helpers/errors_helper.rb
  app/helpers/home_helper.rb
  app/helpers/members_helper.rb
  app/helpers/static_pages_helper.rb
  app/helpers/units_helper.rb
  spec/features/errors_spec.rb
  spec/helpers/companies_helper_spec.rb
  spec/helpers/static_pages_helper_spec.rb
  spec/rails_helper.rb
  spec/requests/companies_request_spec.rb
  spec/requests/errors_request_spec.rb
  spec/support/simplecov.rb
  spec/views/static_pages/about.html.slim_spec.rb
  spec/views/static_pages/contact.html.slim_spec.rb
  spec/views/static_pages/services.html.slim_spec.rb
Labels: ready for review

#88 Fix/user factory
  app/models/user.rb
  spec/factories/users.rb
Labels: ready for review

#86 Fix/company registrations flash errors validation errors
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/users.scss
  app/controllers/companies_controller.rb
  app/forms/company_registrations_form.rb
  app/views/companies/_company_registration_form.slim
  spec/controllers/companies_controller_spec.rb
Labels: ready for review

#84 Render page 404 if not found
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
Labels: ready for review

#83 Feature/owner create units
  app/controllers/application_controller.rb
  app/controllers/units_controller.rb
  app/models/guest.rb
  app/models/user.rb
  app/policies/unit_policy.rb
  app/views/layouts/_nav.html.slim
  app/views/units/_unit.html.slim
  app/views/units/index.html.slim
  app/views/units/show.html.slim
  db/schema.rb
  spec/controllers/units_controller_spec.rb
  spec/features/unit_crud_spec.rb
Labels: ready for review

#82 Fix users-show view
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/users.scss
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/views/users/_users.html.slim
  app/views/users/show.html.slim
  spec/features/create_user_spec.rb
Labels: ready for review

#91 Fix/Feedback
  app/assets/stylesheets/feedbacks.scss
  app/assets/stylesheets/static_pages.scss
  app/controllers/feedbacks_controller.rb
  app/controllers/static_pages_controller.rb
  app/models/feedback.rb
  app/views/feedbacks/index.html.slim
  app/views/feedbacks/new.html.slim
  app/views/feedbacks/show.html.slim
  app/views/static_pages/contact.html.slim
  config/routes.rb
  db/migrate/20200427154143_rename_describe_to_message_in_feedbacks.rb
  db/schema.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/factories/feedbacks.rb
  spec/features/user_leaves_feedback_spec.rb
  spec/features/user_visit_feedbacks_page_spec.rb
  spec/models/feedback_spec.rb
Labels: ready for review

#94 Fix/authenticate user for controllers
  app/controllers/companies_controller.rb
  app/controllers/members_controller.rb
  app/controllers/users_controller.rb
  app/forms/company_registrations_form.rb
  app/views/users/_form.html.slim
  spec/controllers/companies_controller_spec.rb
  spec/controllers/members_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/company_registrations_form.rb
  spec/features/company_registration_spec.rb
  spec/features/create_company_spec.rb
  spec/features/create_user_spec.rb
  spec/features/user_looks_information_about_company_other_user_spec.rb
Labels: question

#95 Fix/modify unit tree structure
  app/assets/stylesheets/units.scss
  app/javascript/packs/application.js
  app/javascript/packs/unit-tree.js
  app/views/companies/show.html.slim
  app/views/units/_unit.html.slim
  app/views/units/_unit_tree_structure.html.slim
  app/views/units/index.html.slim
  app/views/units/show.html.slim
Labels: ready for review

#92 Add annotate gem
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/company.rb
  app/models/feedback.rb
  app/models/unit.rb
  app/models/user.rb
  app/models/users_companies_relationship.rb
  lib/tasks/auto_annotate_models.rake
  spec/factories/companies.rb
  spec/factories/feedbacks.rb
  spec/factories/units.rb
  spec/factories/users.rb
  spec/factories/users_companies_relationships.rb
  spec/models/feedback_spec.rb
Labels: ready for review

#96 Fix unit urls/current company
  app/controllers/application_controller.rb
  app/controllers/units_controller.rb
  app/models/guest.rb
  app/models/user.rb
  app/policies/unit_policy.rb
  app/views/companies/show.html.slim
  app/views/units/_unit.html.slim
  app/views/units/_unit_form.html.slim
  app/views/units/index.html.slim
  app/views/units/show.html.slim
  config/routes.rb
  spec/controllers/units_controller_spec.rb
  spec/features/unit_crud_spec.rb
Labels: ready for review
